[package]
name = "podcast-downloader"
version = "0.1.0"
authors = ["Jane Keibler <wanderingelf14@gmail.com>"]
license = "GPLv3"

[dependencies]
reqwest = "0.4.0"
rss = "0.4.0"
clap = { version = "2.20.5", features = ["yaml"] }
